[green_agent]
agentbeats_id = "019d1c38-8835-7f40-8d2d-43ac8c66b2ff"
env = {}

[[participants]]
agentbeats_id = "019d1c3e-edbe-7ea2-8970-ed047e6c6dea"
name = "agent"

[participants.env]
MAX_CONTEXTS = "5"

[config]
# Add your assessment config here
