[green_agent]
image = "osworld-green:latest"
env = { LOG_LEVEL = "INFO" }

[[participants]]
image = "osworld-dummy-purple:latest"
name = "agent"
env = { LOG_LEVEL = "INFO" }

[config]
# Add your assessment config here
domain = "os"
example_id = "5ced85fc-fa1a-4217-95fd-0fb530545ce2"
